[tool.poetry]
name = "aiogram-template"
version = "0.1.0"
description = ""
authors = ["rdfsx <m315498@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
aiogram = "^2.15"
environs = "^9.3.4"
loguru = "^0.5.3"
aiogram-broadcaster = "^0.0.6"
aiofile = "^3.7.2"
PyYAML = "^6.0"
python-i18n = {extras = ["YAML"], version = "^0.3.9"}
beanie = "^1.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
